# -*- coding: utf-8 -*-
import base64
import logging

from markupsafe import Markup, escape

from odoo import _, api, fields, models
from odoo.exceptions import UserError

from .whatsapp_account import normalize_number

_logger = logging.getLogger(__name__)

try:
    import requests
except ImportError:  # pragma: no cover - declared in external_dependencies
    requests = None

MAX_RETRIES = 3

# Twilio message resource status -> our state.
TWILIO_STATUS_MAP = {
    "accepted": "outgoing",
    "scheduled": "outgoing",
    "queued": "outgoing",
    "sending": "outgoing",
    "sent": "sent",
    "delivered": "delivered",
    "read": "read",
    "receiving": "received",
    "received": "received",
    "failed": "failed",
    "undelivered": "failed",
    "canceled": "cancelled",
}


class WhatsappMessage(models.Model):
    _name = "whatsapp.message"
    _description = "WhatsApp Message"
    _order = "id desc"

    conversation_id = fields.Many2one(
        "whatsapp.conversation", ondelete="cascade", index=True
    )
    account_id = fields.Many2one("whatsapp.account", required=True, index=True)
    direction = fields.Selection(
        [("inbound", "Inbound"), ("outbound", "Outbound")],
        required=True, index=True,
    )
    number = fields.Char("Customer Number", required=True, index=True)
    partner_id = fields.Many2one("res.partner", string="Contact", index=True)
    ticket_id = fields.Many2one(
        related="conversation_id.ticket_id", store=True, string="Ticket"
    )

    body = fields.Text()
    message_type = fields.Selection(
        [("text", "Text"), ("template", "Template"), ("media", "Media")],
        default="text", required=True,
    )
    template_id = fields.Many2one("whatsapp.template", string="Template")
    content_variables = fields.Char(
        help="JSON payload sent to Twilio as ContentVariables.",
    )
    media_url = fields.Text(help="One media URL per line.")
    attachment_ids = fields.Many2many("ir.attachment", string="Attachments")

    twilio_sid = fields.Char("Twilio SID", index=True, copy=False)
    state = fields.Selection(
        [
            ("draft", "Draft"),
            ("outgoing", "Queued"),
            ("sent", "Sent"),
            ("delivered", "Delivered"),
            ("read", "Read"),
            ("received", "Received"),
            ("failed", "Failed"),
            ("cancelled", "Cancelled"),
        ],
        default="draft", required=True, index=True, copy=False,
    )
    error_code = fields.Char(readonly=True, copy=False)
    error_message = fields.Char(readonly=True, copy=False)
    retry_count = fields.Integer(default=0, copy=False)

    sent_date = fields.Datetime(readonly=True, copy=False)
    delivered_date = fields.Datetime(readonly=True, copy=False)
    author_id = fields.Many2one(
        "res.users", string="Sent by", default=lambda self: self.env.user
    )
    is_bot = fields.Boolean(
        "Sent by Bot", help="Generated by the scripted flow rather than an agent."
    )
    chatter_message_id = fields.Many2one(
        "mail.message", string="Chatter Entry", readonly=True, copy=False,
        help="The ticket chatter entry mirroring this message. Set once, so a "
             "resync never duplicates history.",
    )
    is_command = fields.Boolean(
        "Agent Command", readonly=True,
        help="An agent's texted command, or the answer to one. Carries no "
             "conversation, so it never reaches the queue or a customer.",
    )
    name = fields.Char(compute="_compute_name", store=True)

    _sql_constraints = [
        ("twilio_sid_uniq", "unique(twilio_sid)",
         "This Twilio message has already been recorded."),
    ]

    @api.depends("direction", "number", "body", "template_id")
    def _compute_name(self):
        for record in self:
            preview = (record.body or record.template_id.name or "").strip()
            preview = preview.replace("\n", " ")
            if len(preview) > 60:
                preview = preview[:57] + "..."
            arrow = "<-" if record.direction == "inbound" else "->"
            record.name = "%s %s %s" % (arrow, record.number or "", preview)

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if vals.get("number"):
                vals["number"] = normalize_number(vals["number"])
            if vals.get("direction") == "outbound" and not vals.get("state"):
                vals["state"] = "outgoing"
        return super().create(vals_list)

    # ------------------------------------------------------------------
    # Sending
    # ------------------------------------------------------------------
    def _status_callback_url(self):
        self.ensure_one()
        return self.account_id.status_webhook_url

    def action_send(self):
        """Send queued outbound messages, one Twilio call each.

        Each message is committed independently so one bad number cannot roll
        back a whole batch sent from a cron.
        """
        for record in self.filtered(lambda m: m.direction == "outbound"):
            if record.state in ("sent", "delivered", "read"):
                continue
            record._send_one()
        return True

    def _send_one(self):
        self.ensure_one()
        account = self.account_id.sudo()
        media_urls = [u.strip() for u in (self.media_url or "").splitlines() if u.strip()]
        try:
            response = account._send_raw(
                self.number,
                body=self.body if self.message_type != "template" else None,
                media_urls=media_urls or None,
                content_sid=self.template_id.content_sid if self.message_type == "template" else None,
                content_variables=self.content_variables,
                status_callback=self._status_callback_url(),
            )
        except UserError as exc:
            self._mark_failed(code=False, message=str(exc))
            return False
        if not response.get("_ok"):
            self._mark_failed(
                code=response.get("code"),
                message=response.get("message") or _("HTTP %s") % response.get("_http_status"),
            )
            return False
        self.write({
            "twilio_sid": response.get("sid"),
            "state": TWILIO_STATUS_MAP.get(response.get("status"), "sent"),
            "sent_date": fields.Datetime.now(),
            "error_code": False,
            "error_message": False,
        })
        self._post_to_ticket()
        return True

    def _mark_failed(self, code=None, message=None):
        self.ensure_one()
        self.write({
            "state": "failed",
            "error_code": code and str(code) or False,
            "error_message": (message or "")[:500] or False,
            "retry_count": self.retry_count + 1,
        })
        _logger.warning(
            "WhatsApp message %s to %s failed (%s): %s",
            self.id, self.number, code, message,
        )

    def action_retry(self):
        self.filtered(lambda m: m.state == "failed").write({
            "state": "outgoing", "retry_count": 0,
        })
        return self.action_send()

    def action_cancel(self):
        return self.filtered(
            lambda m: m.state in ("draft", "outgoing", "failed")
        ).write({"state": "cancelled"})

    # ------------------------------------------------------------------
    # Status callbacks
    # ------------------------------------------------------------------
    @api.model
    def _apply_status_callback(self, params):
        """Handle a Twilio StatusCallback POST."""
        sid = params.get("MessageSid") or params.get("SmsSid")
        if not sid:
            return False
        message = self.sudo().search([("twilio_sid", "=", sid)], limit=1)
        if not message:
            return False
        status = (params.get("MessageStatus") or params.get("SmsStatus") or "").lower()
        values = {"state": TWILIO_STATUS_MAP.get(status, message.state)}
        if values["state"] == "delivered" and not message.delivered_date:
            values["delivered_date"] = fields.Datetime.now()
        if params.get("ErrorCode"):
            values["error_code"] = params["ErrorCode"]
            values["error_message"] = params.get("ErrorMessage") or _(
                "Twilio error %s"
            ) % params["ErrorCode"]
        message.write(values)
        return True

    # ------------------------------------------------------------------
    # Inbound media
    # ------------------------------------------------------------------
    def _download_media(self, urls):
        """Pull inbound media from Twilio and store it as attachments.

        Twilio media URLs need the account credentials, so we fetch them
        server-side rather than leaving dead links in the chatter.
        """
        self.ensure_one()
        if requests is None or not urls:
            return
        account = self.account_id.sudo()
        attachments = self.env["ir.attachment"]
        for index, url in enumerate(urls):
            try:
                response = requests.get(
                    url, auth=(account.account_sid, account.auth_token), timeout=30
                )
                response.raise_for_status()
            except Exception as exc:  # media is best-effort, never block intake
                _logger.warning("Could not fetch WhatsApp media %s: %s", url, exc)
                continue
            content_type = response.headers.get("Content-Type", "")
            extension = content_type.split("/")[-1].split(";")[0] or "bin"
            attachments |= self.env["ir.attachment"].sudo().create({
                "name": "whatsapp-%s-%s.%s" % (self.id, index + 1, extension),
                "datas": base64.b64encode(response.content),
                "res_model": self._name,
                "res_id": self.id,
                "mimetype": content_type or False,
            })
        if attachments:
            self.attachment_ids = [(6, 0, attachments.ids)]

    # ------------------------------------------------------------------
    # Chatter mirroring
    # ------------------------------------------------------------------
    def _post_to_ticket(self):
        """Mirror the message into the ticket chatter so agents see one thread.

        Idempotent: each message remembers the chatter entry it produced, so
        re-running this (or the Sync Transcript button) never duplicates the
        history.
        """
        for record in self:
            ticket = record.conversation_id.ticket_id
            if not ticket or record.chatter_message_id:
                continue
            mode = ticket.team_id.whatsapp_log_mode or "all"
            if mode == "none":
                continue
            if mode == "human" and record.is_bot:
                continue

            who = record.author_id.name or (
                _("Bot") if record.is_bot else record.partner_id.display_name
            )
            heading = (
                _("WhatsApp from %s") % (record.partner_id.display_name
                                         or record.number)
                if record.direction == "inbound"
                else _("WhatsApp to %(who)s, sent by %(by)s",
                       who=record.partner_id.display_name or record.number,
                       by=who or _("the system"))
            )
            # escape() returns Markup, and Markup.replace() escapes its
            # arguments -- so the line break has to be spliced into the plain
            # escaped string and re-wrapped, or the reader sees "<br/>".
            escaped = str(escape(record.body or ""))
            rendered = (Markup(escaped.replace("\n", "<br/>")) if escaped
                        else escape(_("(media)")))
            body = Markup("<p><b>%s</b></p><p>%s</p>") % (heading, rendered)

            # Attribute the entry to whoever actually said it, so the chatter
            # reads like a conversation rather than a wall of OdooBot.
            if record.direction == "inbound":
                author = record.partner_id or record.conversation_id.partner_id
            elif record.is_bot:
                author = self.env.ref("base.partner_root", raise_if_not_found=False)
            else:
                author = record.author_id.partner_id

            posted = ticket.with_context(ibq_whatsapp_relay_skip=True).sudo().message_post(
                body=body,
                author_id=author.id if author else False,
                message_type="comment",
                subtype_xmlid="mail.mt_note",
                date=record.create_date,
                attachment_ids=record.attachment_ids.ids or None,
            )
            record.sudo().chatter_message_id = posted

    # ------------------------------------------------------------------
    # Cron
    # ------------------------------------------------------------------
    @api.model
    def _cron_send_queued(self, limit=100):
        queued = self.search([
            ("direction", "=", "outbound"),
            ("state", "in", ("outgoing", "failed")),
            ("retry_count", "<", MAX_RETRIES),
        ], limit=limit, order="id asc")
        for message in queued:
            message._send_one()
            # Isolate failures: one unreachable number must not lose the batch.
            self.env.cr.commit()
        return True
